name: cpf_cnpj_validator
description: A lib to validate, format, strip and generate CPF and CNPJ numbers from Brazil.
version: 1.0.5
author: Leonardo Caldas <leonardo.ferreira.caldas@gmail.com>
homepage: https://github.com/leonardocaldas/flutter-cpf-cnpj-validator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter